# .github/workflows/trufflehog-secret-scan.yml:
# Scans the repository for secrets using TruffleHog
# Based on:
# https://github.com/trufflesecurity/trufflehog/blob/v3.81.1/README.md#octocat-trufflehog-github-action

# yamllint disable rule:line-length
---
name: "Scan for Secrets"

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches-ignore:
      - dependabot/**

jobs:
  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Calculate Fetch Depth for Shallow Clone
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "depth=$(( $(jq length <<< '${{ toJson(github.event.commits) }}') + 2 ))" \
              >> $GITHUB_ENV
            echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "depth=$(( ${{ github.event.pull_request.commits }} + 2 ))" \
              >> $GITHUB_ENV
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.branch }}
          fetch-depth: ${{ env.depth }}

      - name: Run Secret Scanning with TruffleHog
        uses: trufflesecurity/trufflehog@v3.81.0
        with:
          extra_args: --only-verified
