# .github/workflows/trufflehog-secret-scan.yml:
# Scans the repository for secrets using TruffleHog
# Based on:
# https://github.com/trufflesecurity/trufflehog/blob/v3.81.1/README.md#octocat-trufflehog-github-action
---
name: Secret Scanning

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches-ignore:
      - dependabot/**

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Secret Scanning with TruffleHog
        uses: trufflesecurity/trufflehog@v3.81.0
        with:
          extra_args: --only-verified
